# Generated by Django 4.2.30 on 2026-05-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_price', models.IntegerField()),
                ('professor_rate', models.IntegerField()),
                ('per_lesson', models.BooleanField(default=False)),
                ('lessons_in_month', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='professors_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notations', models.TextField(blank=True, default='Поки що немає нотаток', max_length=1000)),
                ('courses', models.ManyToManyField(related_name='students', to='analytics.chesscourse')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='analytics.professor')),
            ],
        ),
    ]
