# Generated by Django 4.2.30 on 2026-05-03 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='students_courses',
            field=models.ManyToManyField(related_name='course_students', to='analytics.chesscourse'),
        ),
        migrations.AlterField(
            model_name='chesscourse',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='picture',
            field=models.ImageField(null=True, upload_to='professors_pics/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='notations',
            field=models.TextField(default='Поки-що немає нотатків', max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_students', to='analytics.professor'),
        ),
    ]
